-- Feed generator: replaces the standalone aparasion/rss-generator repo for
-- LocReport's own sources. Each row is one scrape target — either an HTML
-- listing page (CSS selectors) or an existing RSS/Atom feed re-filtered by
-- keyword — plus the most recently generated output and run status.
--
-- Served publicly at /api/feeds/[name] (Content-Type: application/rss+xml),
-- so an rss_sources row can point at that URL exactly like any other feed.
-- Regenerated by POST /api/scraped-sources/run (Vercel Cron or the "Run now"
-- button in /admin/scraped-sources) — see vercel.json for the schedule.
create table if not exists scraped_sources (
  id uuid primary key default gen_random_uuid(),
  name text unique not null,
  -- 'html': scrape a listing page with CSS selectors.
  -- 'rss':  fetch an existing feed and re-filter its items by keyword.
  type text not null default 'html' check (type in ('html', 'rss')),
  url text not null,
  active boolean not null default true,

  -- CSS selectors — html type only. linkSelector may be the literal string
  -- "self" (the article element itself is the anchor).
  article_selector text,
  title_selector text,
  link_selector text,
  description_selector text,
  date_selector text,
  -- Substring (or /regex/ — matched with .includes today, not compiled) that
  -- a candidate article link must contain to be kept.
  link_pattern text,

  -- Feed metadata overrides. Fall back to "<name> Feed" / a generic
  -- description when null.
  feed_title text,
  feed_description text,

  -- { keywords: string[], minMatches?: number, checkFullContent?: boolean,
  --   maxScan?: number }. Null = no filtering, keep everything found.
  content_filter jsonb,

  -- Per-article relevance memo so a content-filtered source doesn't
  -- re-fetch and re-classify the same article on every run:
  -- { [articleUrl]: { relevant: boolean, checkedAt: string } }
  classified_links jsonb not null default '{}'::jsonb,

  -- Most recent output, served as-is by /api/feeds/[name] until the next run.
  generated_xml text,
  last_run_at timestamptz,
  last_status text check (last_status in ('success', 'error')),
  last_error text,
  last_item_count int,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Service-role access only (admin API routes + the cron/run endpoint) —
-- same pattern as subscribers / llm_pricing_quotes.
alter table scraped_sources enable row level security;

-- Seed from aparasion/rss-generator's config.json — the localization-industry
-- sources only. That repo's config.json also feeds a separate project
-- (healthspanwire: FierceBiotech-Health-Longevity, Nature-Aging-Longevity),
-- which is out of scope here and needs its own migration off GitHub Actions.
insert into scraped_sources (name, type, url, article_selector, title_selector, link_selector, description_selector, date_selector, link_pattern, feed_title, feed_description, content_filter)
values
  ('TAUS-Blog', 'html', 'https://www.taus.net/resources/blog/',
    '.article-card', '.text-xl.font-semibold', 'a[href*=''/resources/blog/'']:not([href*=''/category/''])', '.line-clamp-5', '.text-xs.text-gray-950', '/resources/blog/',
    null, null, null),
  ('DATAmundi-Newsroom', 'html', 'https://datamundi.ai/newsroom/',
    '.e-loop-item', '.elementor-widget-theme-post-title h3 a', '.elementor-widget-theme-post-title h3 a', '', '', null,
    null, null, null),
  ('GALA-Global', 'html', 'https://www.gala-global.org/news/',
    '.articles .article', '.c-article-list-full-width__wrapper', '.c-article-list-full-width__wrapper', '.c-article-list__description', '.c-article-list__date', null,
    null, null, null),
  ('XTM-Blog', 'html', 'https://xtm.cloud/blog/',
    '.post-card.cpt-listing-single', '.post-card-title', 'a.post-card-link-wrapper', '.post-card-caption', '', null,
    null, null, null),
  ('LingopalAI', 'html', 'https://lingopal.ai/industrynews-blog',
    'a.card-link', 'h2.card-title', 'self', 'p.card-desc', 'time', '/industrynews-blog/article/',
    null, null, null),
  ('phrase-blog', 'html', 'https://phrase.com/blog/',
    '.wp-block-post', '.wp-block-post-title', 'a.wp-block-post-excerpt__more-link', '.wp-block-post-excerpt', '.wp-block-post-meta__dates-primary', null,
    null, null, null),
  ('lokalise-blog', 'html', 'https://lokalise.com/blog/',
    '[class*=''BlogCard-module'']', 'h2', 'a[href*=''/blog/'']', 'p.lok-text-body-regular-medium', '.lok-text-body-small', null,
    null, null, null),
  ('crowdin-blog', 'html', 'https://crowdin.com/blog',
    '.group', 'h3', 'a', 'p', 'span:contains(''min read'')', null,
    null, null, null),
  ('PRNewswire-L10N', 'html', 'https://www.prnewswire.com/news-releases/news-releases-list/',
    '.release-list-item', 'h3', 'a', '.release-date', '.release-date', null,
    null, null,
    '{"keywords":["localization","localisation","l10n","translation","translator","translated","translating","multilingual","multi-language","internationalization","internationalisation","i18n","globalization","globalisation","g11n","language service","language services","language service provider","LSP","machine translation","MT provider","transcreation","translation management","TMS","terminology management","language technology","subtitling","dubbing","content localization","website localization","software localization","game localization","global content"],"minMatches":1,"checkFullContent":false,"maxScan":50}'::jsonb),
  ('RWS-media-centre', 'html', 'https://www.rws.com/about/media-centre/',
    'a[href^=''/about/media-centre/press-releases/'']', 'h3', '', 'p', 'time', null,
    null, null, null),
  ('transperfect-news-and-press', 'html', 'https://www.transperfect.com/about/news-and-press/',
    '.views-row', '.views-field-title a', '.views-field-title a', '', '.datetime', null,
    null, null, null),
  ('Cohere-Newsroom-L10N', 'html', 'https://cohere.com/newsroom/articles',
    'div[class*=''grid-cols-5'']', 'h2', 'a[href^=''/blog/'']', '', '> p', '/blog/',
    'Cohere Newsroom — Language & Translation', 'Cohere newsroom articles filtered for language, translation, and linguistics topics',
    '{"keywords":["language","languages","linguist","translate","translation","translations"],"minMatches":1,"checkFullContent":false,"maxScan":50}'::jsonb),
  ('OpenAI-News-L10N', 'rss', 'https://openai.com/news/rss.xml',
    null, null, null, null, null, null,
    'OpenAI News — Translation & Localization', 'OpenAI news posts filtered for translation, linguistics, and localization topics',
    '{"keywords":["translat","linguist","localize"],"minMatches":1,"checkFullContent":false,"maxScan":100}'::jsonb)
on conflict (name) do nothing;
